global:
  cloud:
    # -- If cloud support should be enabled.
    enabled: false

replicaCount: 1

nameOverride: ""
fullnameOverride: "sf-chart"

sf-api:
  imagePullSecrets:
    - name: sfimages

sf-status:
  imagePullSecrets:
    - name: sfimages

sf-explorer:
  imagePullSecrets:
    - name: sfimages

sf-node:
  imagePullSecrets:
    - name: sfimages

ingress:
  enabled: true
  className: ""
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    kubernetes.io/tls-acme: "true"
  hosts:
    - host: api.local
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: sf-hasura
              port:
                number: 80
    - host: status.local
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: sf-status
              port:
                number: 80
    - host: explorer.local
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: sf-explorer
              port:
                number: 80
    - host: api.node.local
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: sf-api
              port:
                number: 80
    - host: node.local
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: sf-node
              port:
                number: 9944
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
